// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghtdsyjuatsfombkrusu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdodGRzeWp1YXRzZm9tYmtydXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTU3NTUsImV4cCI6MjA2ODY3MTc1NX0.r_fHxlAx7y_Qpu-n92V_Keg8qvlaMrK_q-5806aqv2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});